app = "xiaozhi-mcphub"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  SMART_ROUTING_ENABLED = "false"
  ENABLE_CORS = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"

